# Generated by Django 4.2.9 on 2024-02-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.IntegerField()),
                ('room', models.IntegerField()),
                ('defaultevent', models.BooleanField()),
                ('event', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
