# Generated by Django 4.2.9 on 2024-02-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.CharField(max_length=4),
        ),
    ]
