# Generated by Django 4.2.9 on 2024-02-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('max', models.IntegerField()),
                ('room', models.TextField()),
            ],
        ),
    ]
